eshop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views
from enterprise.views import password_reset_request

urlpatterns = [ 
    path('admin/', admin.site.urls),
    path("password_reset",password_reset_request.as_view(), name="admin_password_reset"),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="password_reset_confirm.html"), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'), name='password_reset_complete'),      
    path('', include('user.urls')),
    path('enterprise/',include('enterprise.urls'))
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from .views import *
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
#User Basic Start
path('',Index.as_view(),name='index'),
path('faqs',Faqs.as_view(),name='faqs'),
path('aboutus',Aboutus.as_view(),name='aboutus'),
path('login/',Login.as_view(),name='login'),
path('logout/',Logout.as_view(),name='logout'),
path('registeration/',Registeration.as_view(),name='registeration'),
path('forgotpassword/',ForgotPassword.as_view(),name='user_forgot_password'),
path('otpverification/',OtpVerification.as_view(),name='user_otp_verification'),
path('changepassword/',ChangePassword.as_view(),name='user_change_password'),
path('profile/',Profile.as_view(),name='user_profile'),
path('userchangepassword/',ProfileChangePassword.as_view(),name='profile_user_change_password'),
path('address/',UserAddress.as_view(),name='user_address'),
path('addressdetail/<id>',AddressDetail.as_view(),name='address_detail'),
path('deleteaddress/<id>',DeleteAddress.as_view(),name='delete_address'),
path('products/<id>',AllProducts.as_view(),name='all_products'),
path('product/<id>',ProductDetail.as_view(),name='product_detail'),
path('placeorder/<slug>',PlaceOrder.as_view(),name='place_order'),
path('orderhistory',OrderHistory.as_view(),name='order_history'),
path('orderdelete/<orderno>',OrderHistoryDelete.as_view(),name='order_history_delete'),
path('orderdetail/<orderno>',OrderDetail.as_view(),name='user_order_detail'),
path('addtocart/<id>',AddItem.as_view(),name='add_to_cart'),
path('removecart/<id>',RemoveItem.as_view(),name='remove_from_cart'),
path('cart',CartList.as_view(),name="cart")
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

user/models.py
from django.db import models
from django.core.validators import RegexValidator, FileExtensionValidator
from django.utils.timezone import now
from django.db.models import signals
import uuid
from djongo import models
from enterprise.models import Products

class ParanoidModelManager(models.Manager):
    def get_queryset(self):
        return super(ParanoidModelManager, self).get_queryset().filter(deleted_at__isnull=True)


class Users(models.Model):
    _id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user_name = models.CharField(("UserName"), max_length=50,null=False,blank=False)
    user_password = models.CharField(("Password"), max_length=64,null=False,blank=False)
    user_email = models.EmailField(("E-mail"), max_length=254,blank=False,unique=True)
    user_photo = models.ImageField(("Profile-photo"), upload_to='User/profile_photo', validators=[FileExtensionValidator(['jpg','jpeg','png'])],height_field=None, width_field=None, max_length=None)
    user_age = models.PositiveIntegerField(("Age"),blank=False)
    user_gender = models.CharField(("Gender"), max_length=50,blank=False)
    phoneNumberRegex = RegexValidator(regex = r"^\+?1?\d{10}$")
    user_contact = models.CharField(validators = [phoneNumberRegex], max_length = 10, unique = True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    deleted_at = models.DateTimeField(blank=True, null=True, default=None)
    objects = ParanoidModelManager()


    class Meta:
           verbose_name_plural = "Users"

    def __str__(self):
        return self.user_name

    def delete(self, hard=False, **kwargs):
        cls = self.__class__
        signals.pre_delete.send(sender=cls, instance=self)

        if hard:
            super(Users, self).delete()
        else:
            self.deleted_at = now()
            self.save()


class Address(models.Model):
    _id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(Users, verbose_name=("User"), on_delete=models.CASCADE)
    country = models.CharField(("Country"), max_length=50)
    state = models.CharField(("State"), max_length=50)
    city = models.CharField(("City"), max_length=50)
    pin_code =  models.PositiveIntegerField(("Pincode"))
    postal_address = models.TextField(("Postal Address"))
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    deleted_at = models.DateTimeField(blank=True, null=True, default=None)
    objects = ParanoidModelManager()

    class Meta:
           verbose_name_plural = "Address"

    def delete(self, hard=False, **kwargs):
        if hard:
            super(Cart, self).delete()
        else:
            self.deleted_at = now()
            self.save()

    def __str__(self):
        return self.postal_address +', '+self.city +', '+ self.state +', '+ self.country

class Cart(models.Model):
    _id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(Users, verbose_name=("user"), on_delete=models.CASCADE)
    product_items = models.ForeignKey(Products, verbose_name=("Product-item"), on_delete=models.CASCADE)
    qty = models.PositiveIntegerField(("product_qty"),default=1)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    deleted_at = models.DateTimeField(blank=True, null=True, default=None)
    objects = ParanoidModelManager()

    class Meta:
           verbose_name_plural = "Cart"
        
 
    def delete(self, hard=False, **kwargs):
        if hard:
            super(Cart, self).delete()
        else:
            self.deleted_at = now()
            self.save()
    
    def __str__(self):
        return self.user.user_name


class Order(models.Model):
    _id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    order_no = models.PositiveIntegerField(("Order-No"))
    user = models.ForeignKey(Users, verbose_name=("user"), on_delete=models.CASCADE)
    product = models.ForeignKey(Products, verbose_name=("product"), on_delete=models.CASCADE)
    qty = models.PositiveIntegerField(("Product-qty"),default=1)
    total = models.PositiveIntegerField(("Total-Amount"))
    address = models.TextField(("Address"))
    payment_method = models.CharField(("Payment-Method"), max_length=50)
    CHOICES = [('0','Pending'),('1','Approved'),('2','Dispatched'),('3','Delievered'),('4','Cancelled')]
    status = models.CharField(("status"),choices=CHOICES, max_length=50)
    ordered_date = models.DateField(("Ordered-Date"), auto_now=False, auto_now_add=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    deleted_at = models.DateTimeField(blank=True, null=True, default=None)
    objects = ParanoidModelManager()


    def delete(self, hard=False, **kwargs):
        if hard:
            super(Order, self).delete()
        else:
            self.deleted_at = now()
            self.save()

user/views.py
from django.db.models.aggregates import Sum
from .tasks import mail_sender_enterprise, mail_sender_user
from django.shortcuts import render,redirect
from django.urls import reverse
from django.contrib import messages
from django.views import View
from .models import Users,Order,Cart,Address
from django.db.models import Q
from django.conf import settings
from django.core.mail import send_mail
from enterprise.models import Categories,Products
from .forms import AddressForm, RegisterForm,ProfileForm
import random
from django.core.paginator import Paginator
from django.db.models import  Count
import hashlib

class Faqs(View):
	def get(self,request):
		if request.session.get('users_key'):
			return render(request,'user/faqs.html',{'users':True})
		else:
			return render(request,'user/faqs.html')

class Aboutus(View):
	def get(self,request):
		if request.session.get('users_key'):
			return render(request,'user/aboutus.html',{'users':True})
		else:
			return render(request,'user/aboutus.html')


class ForgotPassword(View):
	def get(self,request):
		return render(request,'user/email_verification.html')
	
	def post(self,request):
		user_email = request.POST['email']
		try:
			user_data = Users.objects.get(user_email=user_email)
			request.session['temp_data'] = str(user_data._id)
			generated_otp = random.randint(1111,9999)
			request.session['otp']=generated_otp	
			subject = 'Acount Recovery'
			message = f'''your otp for account recovery is {generated_otp}'''
			email_from = settings.EMAIL_HOST_USER
			recepient  = [user_email,]
			send_mail(subject, message, email_from, recepient)
			return redirect(reverse('user_otp_verification'))
		except:
			messages.error(request,'Email id not found try again.')
			return redirect(reverse('user_forgot_password'))


class OtpVerification(View):
	def get(self,request):
		return render(request,'user/otp.html')

	def post(self,request):
		user_otp = request.POST['otp']
		if user_otp == str(request.session.get('otp')):
			return redirect(reverse('user_change_password'))
		else:
			messages.error(request,'Wrong otp try again.')
			return redirect(reverse('user_otp_verification'))


class ChangePassword(View):
	def get(self,request):
		return render(request,'user/change_password.html')

	def post(self,request):
		password = request.POST['password']
		confirm_password = request.POST['confirm_password']
		if password == confirm_password:
			user_id = request.session.get('temp_data')
			user_data = Users.objects.get(_id=user_id)
			user_data.user_password = hashlib.sha256(str.encode(confirm_password)).hexdigest()
			user_data.save()
			del request.session['temp_data']
			del request.session['otp']
			return redirect(reverse('login'))
		else:
			messages.error(request,'Password does not match.')
			return redirect(reverse('user_change_password'))


class Login(View):
	def get(self,request):
		return render(request,'user/login.html')

	def post(self,request):
		user_mail = request.POST['usermail']
		user_password = request.POST['password']
		try:
			fetched_data = Users.objects.filter(user_email=user_mail).first()
			if fetched_data != None and hashlib.sha256(str.encode(user_password)).hexdigest() == fetched_data.user_password :
				request.session['users_key'] = str(fetched_data._id)
				return redirect(reverse('index'))
			else:
				raise ValueError() 
		except ValueError:
			messages.error(request,'wrong username or password')
			return redirect(reverse('login')) 
		except:
			messages.error(request,'Login Failed Try Again')
			return redirect(reverse('login')) 


class Registeration(View):
	def get(self,request):
		user_form = RegisterForm()
		address_form = AddressForm()
		return render(request,'user/register.html',{'userform':user_form,'addressform':address_form})

	def post(self,request):
		user_form = RegisterForm(request.POST,request.FILES)
		address_form = AddressForm(request.POST,request.FILES)


		if user_form.is_valid:
			try:
				user_obj = user_form.save(commit=False)
				if user_obj:
					address_form.data._mutable = True
					address_form.data['user'] = user_obj
					address_form.data._mutable = False
					user_form.save()
					address_form.save()
				return redirect(reverse('login'))
			except Exception as e:
				return render(request,'user/register.html',{'userform':user_form,'addressform':address_form})
		else:
			return render(request,'user/register.html',{'userform':user_form,'addressform':address_form})
				

class Logout(View):
	def get(self,request):
		if request.session.get('users_key'):
			del request.session['users_key']
			del request.session['cart_count']
		return redirect(reverse('index'))


class Profile(View):
	def get(self,request):
		if request.session.get('users_key'):
			user_data = Users.objects.get(_id=request.session.get('users_key'))
			form = ProfileForm(instance=user_data)	
			return render(request,'user/profile.html',{'form':form,'users':user_data,'cart_count':request.session['cart_count'],'categories':Categories.objects.all()})
		else:
			return redirect(reverse('login'))

	def post(self,request):
		user_data = Users.objects.get(_id=request.session.get('users_key'))
		form = ProfileForm(request.POST,request.FILES,instance=user_data) 
	
		if request.POST.get('register'):
			if form.is_valid():
				form.save()
				messages.success(request,'Your Profile is updated successfully	')
				return redirect(reverse('user_profile'))
			
			else:
				messages.success(request,'Your Profile is not updated')
				return render(request,'user/profile.html',{'form':form,'users':True})
			

class ProfileChangePassword(View):
	def get(self,request):
		if request.session.get('users_key'):
			return render(request,'user/profile_change_password.html')
		else:
			return redirect(reverse('login'))

	def post(self,request):
		old_password = request.POST['old_password']
		password = request.POST['new_password']
		confirm_password = request.POST['confirm_password']
		if password == confirm_password:
			try:
				user_data = Users.objects.get(_id=request.session.get('users_key'))
				if hashlib.sha256(str.encode(old_password)).hexdigest() == user_data.user_password:
					user_data.user_password = hashlib.sha256(str.encode(confirm_password)).hexdigest()
					user_data.save()
					messages.error(request,'Password Has Successfully Changed')
					return redirect(reverse('user_profile'))
				else: 
					messages.error(request,'Sorry Password not found')
					return redirect(reverse('profile_user_change_password'))
			except:
				messages.error(request,'Sorry Password Not Updated Try Again ')
				return redirect(reverse('profile_user_change_password'))
		else:
			messages.error(request,'Password does not match.')
			return redirect(reverse('profile_user_change_password'))


class UserAddress(View):
	def get(self,request):
		if request.session.get('users_key'):
			address_data = Address.objects.filter(user___id = request.session.get('users_key'))
			cart_data = Cart.objects.filter(user___id = request.session.get('users_key'))

			rendered_data = {
				'users':True,
				'cart_count':cart_data.count(),
				'address':address_data
			}
			return render(request,'user/user_address.html',rendered_data)
		else:
			return redirect(reverse('login'))


class AddressDetail(View):
	def get(self,request,id):
		if request.session.get('users_key'):
			cart_data = Cart.objects.filter(user___id = request.session.get('users_key'))
		
			if id == 'newaddress':
				address_form = AddressForm()
				
			else:
				address_data = Address.objects.get(user___id = request.session.get('users_key'),_id=id)
				address_form = AddressForm(instance=address_data)
				
			rendered_data = {
				'users':True,
				'cart_count':cart_data.count(),
				'addressform':address_form
			}
			return render(request,'user/address_detail.html',rendered_data)
		else:
			return redirect(reverse('login'))

	def post(self,request,id):
		if request.session.get('users_key'):
			if id == 'newaddress':
				user_data = Users.objects.get(_id=request.session.get('users_key'))
				address_form = AddressForm(request.POST)
				address_form.data._mutable = True
				address_form.data['user'] = user_data
				address_form.data._mutable = False
			else:
				address_data = Address.objects.get(user___id = request.session.get('users_key'),_id=id)
				address_form = AddressForm(request.POST,instance=address_data)
			try:
				if address_form.is_valid:
					address_form.save()
					return redirect(reverse('user_address'))
				else:
					messages.error(request,"Sorry Address Could'nt Get Updated Try Again ")
					return redirect(reverse('address_detail', kwargs={'id':id}))
			except:
					messages.error(request,"Sorry Address Could'nt Get Updated Try Again ")
					return redirect(reverse('address_detail', kwargs={'id':id})	)
		else:
			return redirect(reverse('login'))

class DeleteAddress(View):
	def get(self,request,id):
		if request.session.get('users_key'):
			address_data = Address.objects.get(user___id = request.session.get('users_key'),_id=id)
			address_data.delete()
			return redirect(reverse('user_address'))
		else:
			return redirect(reverse('login'))

		
class Index(View):
	def get(self,request):
		category_data = Categories.objects.all()
	
		product_Data = Products.objects.all().order_by('Price')[:8]
		if request.session.get('users_key'):
			cart_data = Cart.objects.filter(user___id=request.session.get('users_key')).count()
			request.session['cart_count'] = cart_data
			rendered_data = {
				'categories': category_data,
				'products':product_Data,
				'users':True,
				'cart_count':request.session['cart_count']
			}
		else:
			rendered_data = {
					'categories':category_data,
					'products':product_Data,
				}
		return render(request,'user/index.html',rendered_data)


class AllProducts(View):
	def get(self,request,id):
		rendered_data = {}
		if request.session.get('users_key'):
			rendered_data["users"] = True
			rendered_data["cart_count"] = request.session['cart_count']
		product_data = Products.objects.filter(product_categories=id)

user/templates/user/aboutus.html
{% extends 'user/user_base.html' %}
{% block title %}About{% endblock title %}
{% load static %}
{% load tagger %}

{% block body %}
<div id="page-content">
    	<!--Page Title-->
    	<div class="page section-header text-center">
			<div class="page-title">
        		<div class="wrapper"><h1 class="page-width">About Us</h1></div>
      		</div>
		</div>
        <!--End Page Title-->
        
        <div class="container">
        	<div class="row">
                <div class="col-12 col-sm-12 col-md-12 col-lg-12 main-col">
                	<div class="text-center mb-4">
                        <h2 class="h2">E-Shop</h2>
                        <div class="rte-setting">
                            <p><strong>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</strong></p>
                            <p>The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from "de Finibus Bonorum et Malorum" by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.</p>
                        </div>
                    </div>
               	</div>
            </div>
            <div class="row">
            	<div class="col-12 col-sm-4 col-md-4 col-lg-4 mb-4"><img class="blur-up lazyload"  src="{% static 'assets/images/about1.jpg'%}"  alt="About Us" /></div>
                <div class="col-12 col-sm-4 col-md-4 col-lg-4 mb-4"><img class="blur-up lazyload"  src="{% static 'assets/images/about2.jpg'%}" alt="About Us" /></div>
                <div class="col-12 col-sm-4 col-md-4 col-lg-4 mb-4"><img class="blur-up lazyload" src="{% static 'assets/images/about3.jpg'%}" alt="About Us" /></div>
            </div>
            <div class="row">
            	<div class="col-12">
                    <h2>Sed ut perspiciatis unde omnis iste natus error</h2>
                    <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, On the other hand, we denounce with righteous indignation and dislike men who are so beguiled and demoralized by the charms of pleasure of the moment, so blinded by desire, that they cannot foresee the pain.</p>
                    <p>simple and easy to distinguish. In a free hour, when our power of choice is untrammelled and when nothing prevents our being able to do what we like best, every pleasure is to be welcomed and every pain avoided. But in certain circumstances and owing to the claims of duty or the obligations of business it will frequently occur that pleasures have to be repudiated and annoyances accepted.</p>
                    <p></p>
                </div>
            </div>
            
            <div class="row">
            	<div class="col-12 col-sm-12 col-md-6 col-lg-6 mb-4">
                	<h2 class="h2">About Web</h2>
                    <div class="rte-setting"><p><strong>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong></p>
                    <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.</p>
                    <p></p>
                    <p>At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga.</p></div>
                </div>
                <div class="col-12 col-sm-12 col-md-6 col-lg-6">
                	<h2 class="h2">Contact Us</h2>
                    <ul class="addressFooter">
                        <li><i class="icon anm anm-map-marker-al"></i><p>55 Gallaxy Enque, 2568 steet, 23568 NY</p></li>
                        <li class="phone"><i class="icon anm anm-phone-s"></i><p>(440) 000 000 0000</p></li>
                        <li class="email"><i class="icon anm anm-envelope-l"></i><p>sales@yousite.com</p></li>
                    </ul>
                    <hr />
                    <ul class="list--inline site-footer__social-icons social-icons">
                        <li><a class="social-icons__link" href="#" target="_blank" title="Belle Multipurpose Bootstrap 4 Template on Facebook"><i class="icon icon-facebook"></i></a></li>
                        <li><a class="social-icons__link" href="#" target="_blank" title="Belle Multipurpose Bootstrap 4 Template on Twitter"><i class="icon icon-twitter"></i> <span class="icon__fallback-text">Twitter</span></a></li>
                        <li><a class="social-icons__link" href="#" target="_blank" title="Belle Multipurpose Bootstrap 4 Template on Pinterest"><i class="icon icon-pinterest"></i> <span class="icon__fallback-text">Pinterest</span></a></li>
                        <li><a class="social-icons__link" href="#" target="_blank" title="Belle Multipurpose Bootstrap 4 Template on Instagram"><i class="icon icon-instagram"></i> <span class="icon__fallback-text">Instagram</span></a></li>
                        <li><a class="social-icons__link" href="#" target="_blank" title="Belle Multipurpose Bootstrap 4 Template on Tumblr"><i class="icon icon-tumblr-alt"></i> <span class="icon__fallback-text">Tumblr</span></a></li>
                        <li><a class="social-icons__link" href="#" target="_blank" title="Belle Multipurpose Bootstrap 4 Template on YouTube"><i class="icon icon-youtube"></i> <span class="icon__fallback-text">YouTube</span></a></li>
                        <li><a class="social-icons__link" href="#" target="_blank" title="Belle Multipurpose Bootstrap 4 Template on Vimeo"><i class="icon icon-vimeo-alt"></i> <span class="icon__fallback-text">Vimeo</span></a></li>
                    </ul>
                </div>
            </div>
        </div>       
    </div>





{% endblock body %}

user/templates/user/address_detail.html
{% extends 'user/user_base.html' %}
{% block title %} Address|Detail {% endblock title %}
{% block body %}
<section class="container-fluid">
   {% if messages %}
	<div>
		{% for message in messages %}
		<div class="alert {% if message.level == 25 %}alert-success {% else %}alert-danger {% endif %} m-2">
			<a class="close" href="#" data-dismiss="alert">×</a>
			{{ message }}
		</div>
		{% endfor %}
	</div>
	{% endif %}

   <div class="address-form">
      <div class="page section-header text-center">
         <div class="page-title">
             <div class="wrapper"><h1 class="page-width">Add Address</h1></div>
         </div>
      </div>
      <!-- <h5 class="text-center">Address Detail</h5> -->
      <form method="POST" class="cart style2">
         {% csrf_token %}
         <table>
            {{addressform.user}}
            <tr>
               <td>{{addressform.country.label}} </td>
               <td>{{addressform.country}}</td>
            </tr>
            <tr>
               <td>{{addressform.state.label}}  </td>
               <td>{{addressform.state}}</td>
            </tr>
            <tr>
               <td>{{addressform.city.label}} </td>
               <td>{{addressform.city}}</td>
            </tr>
            <tr>
               <td>{{addressform.pin_code.label}}</td>
               <td>{{addressform.pin_code}}</td>
            </tr>
            <tr>
               <td>{{addressform.postal_address.label}} </td>
               <td>{{addressform.postal_address}}</td>
            </tr>
            <tr>
               <td colspan="2" class="text-center m-2">
                  <button type="submit" value="Save"  class="btn ">Save</button>
               </td>
            </tr>
         </table>
      </form>
   </div>
</section>




{% endblock body %}

user/templates/user/order_success.html
{% extends 'user/user_base.html' %}
{% block title %}Order Placed Successfully{% endblock title %}

{% block body %}
<section class="container-fluid">
   <div class="success-box">
      <h3>Thank-You</h3>
      <h5>your order is been successfully placed.</h5>
      <p>for more detail checkout order section</p>
   </div>
</section>
{% endblock body %}

user/templates/user/register.html
{% extends 'user/user_base.html' %}
{% block title %}Register{% endblock title %}
{% load static %}
{% load tagger
{% block body %}

<!--Body Content-->
<div id="page-content">
   <!--Page Title-->
   <div class="page section-header text-center">
      <div class="page-title">
         <div class="wrapper">
            <h1 class="page-width">Create an Account</h1>
         </div>
      </div>
   </div>
   <!--End Page Title-->

   <div class="container">
      <div class="row">
         <div class="col-12 col-sm-12 col-md-6 col-lg-6 main-col offset-md-3">
            <div class="mb-4">
               <form method="POST" id="CustomerLoginForm" accept-charset="UTF-8" class="contact-form" enctype="multipart/form-data" >
                  {% csrf_token %}
                  <div class="row">
                     <div class="col-12 col-sm-12 col-md-12 col-lg-12">
                        <div class="form-group">
                           <label for="">Name: </label>
                           {{userform.user_name}}
                        </div>
                     </div>
                     <div class="col-12 col-sm-12 col-md-12 col-lg-12">
                        <div class="form-group">
                           <label for="">Password: </label>
                           {{userform.user_password}}
                        </div>
                     </div>
                     <div class="col-12 col-sm-12 col-md-12 col-lg-12">
                        <div class="form-group">
                           <label for="">Email: </label>
                           {% if userform.user_email.errors %}
                           <p class="formerror">{{userform.user_email.errors.as_text}}
                           <p>
                              {% endif %}
                              {{userform.user_email}}
                        </div>
                     </div>
                     <div class="col-12 col-sm-12 col-md-12 col-lg-12">
                        <div class="form-group">
                           <label for="">Profile Photo : </label>
                           {% if userform.user_photo.errors %}
                           <p class="formerror">{{userform.user_photo.errors.as_text}}
                           </p>
                              {% endif %}
                              {{userform.user_photo}}
                        </div>
                     </div>
                     <div class="col-12 col-sm-12 col-md-12 col-lg-12">
                        <div class="form-group">
                           <label for="">Age: </label>
                           {{userform.user_age}}
                        </div>
                     </div>
                     <div class="col-12 col-sm-12 col-md-12 col-lg-12">
                        <div class="form-group">
                           <label for="">Gender: </label>
                           {{userform.user_gender}}
                        </div>
                     </div>
                     <div class="col-12 col-sm-12 col-md-12 col-lg-12">
                        <div class="form-group">
                           <label for="">Contact-No: </label>
                           {% if userform.user_contact.errors %}
                           <p class="formerror">{{userform.user_contact.errors.as_text}}
                           <p>
                              {% endif %}
                              <input type="number" name="user_contact" maxlength="10" required="" id="id_user_contact">
                        </div>
                     </div>
                     {{addressform.user}}
                     <div class="col-12 col-sm-12 col-md-12 col-lg-12">
                        <div class="form-group">
                           <label for="">Country: </label>
                           {{addressform.country}}
                        </div>
                     </div>
                     <div class="col-12 col-sm-12 col-md-12 col-lg-12">
                        <div class="form-group">
                           <label for="">State: </label>
                           {{addressform.state}}
                        </div>
                     </div>
                     <div class="col-12 col-sm-12 col-md-12 col-lg-12">
                        <div class="form-group">
                           <label for="">City: </label>
                           {{addressform.city}}
                        </div>
                     </div>
                     <div class="col-12 col-sm-12 col-md-12 col-lg-12">
                        <div class="form-group">
                           <label for="">Pincode: </label>
                           {{addressform.pin_code}}
                        </div>
                     </div>
                     <div class="col-12 col-sm-12 col-md-12 col-lg-12">
                        <div class="form-group">
                           <label for="">Postal-Detail: </label>
                           {{addressform.postal_address}}
                        </div>
                     </div>

                  </div>
                  <div class="row">
                     <div class="text-center col-12 col-sm-12 col-md-12 col-lg-12">
                        <input type="submit" class="btn mb-3" value="Create">
                     </div>
                  </div>
               </form>
            </div>
         </div>
      </div>
   </div>

</div>
<!--End Body Content-->

{% endblock body %}